/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hryzx
 */
public class hitungBidang extends javax.swing.JFrame {

    /**
     * Creates new form hitungBidang
     */
    public hitungBidang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelJudul = new javax.swing.JPanel();
        LJudul = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        MenuBidang = new javax.swing.JMenu();
        MenuPersegiPanjang = new javax.swing.JMenuItem();
        MenuLinkaran = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bidang 2 Dimensi");

        LJudul.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        LJudul.setForeground(new java.awt.Color(51, 0, 153));
        LJudul.setText("BIDANG 2 DIMENSI");
        LJudul.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        LJudul.setVerticalAlignment(javax.swing.JLabel.CENTER);

        javax.swing.GroupLayout PanelJudulLayout = new javax.swing.GroupLayout(PanelJudul);
        PanelJudul.setLayout(PanelJudulLayout);
        PanelJudulLayout.setHorizontalGroup(
            PanelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJudulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJudul, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelJudulLayout.setVerticalGroup(
            PanelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJudulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJudul, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );

        MenuBidang.setText("Bidang");

        MenuPersegiPanjang.setText("Persegi Panjang");
        MenuPersegiPanjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MenuPersegiPanjangMouseReleased(evt);
            }
        });
        MenuBidang.add(MenuPersegiPanjang);

        MenuLinkaran.setText("Lingkaran");
        MenuLinkaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MenuLinkaranMouseReleased(evt);
            }
        });
        MenuBidang.add(MenuLinkaran);

        MenuBar.add(MenuBidang);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPersegiPanjangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPersegiPanjangMouseReleased
        bidangPersegiPanjang BPP = new bidangPersegiPanjang();
        BPP.setLocationRelativeTo(this);
        BPP.setVisible(true);
    }//GEN-LAST:event_MenuPersegiPanjangMouseReleased

    private void MenuLinkaranMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLinkaranMouseReleased
        bidangLingkaran BL = new bidangLingkaran();
        BL.setLocationRelativeTo(this);
        BL.setVisible(true);
    }//GEN-LAST:event_MenuLinkaranMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hitungBidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hitungBidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hitungBidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hitungBidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hitungBidang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LJudul;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuBidang;
    private javax.swing.JMenuItem MenuLinkaran;
    private javax.swing.JMenuItem MenuPersegiPanjang;
    private javax.swing.JPanel PanelJudul;
    // End of variables declaration//GEN-END:variables
}
