
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hryzx
 */
public class AplikasiGajiPegawai extends javax.swing.JFrame {
    static String jenisPegawai[] = {"PNS", "Tetap non PNS", "Kontrak"},
            jabatan[] = {"Kepala Bagian", "Wakil Kepala Bagian", "Staff"};
    DefaultComboBoxModel<String> mdl = new DefaultComboBoxModel(jenisPegawai),
                                 mdl1 = new DefaultComboBoxModel(jabatan);

    static Object kolom[] = {"Nama", "Jenis Pegawai", "Jabatan",
                             "Gaji Kotor", "Gaji Bersih"};
    int baris = 0;
    DefaultTableModel tbl = new DefaultTableModel(kolom, baris);

    static double gajiPokok[][] = {{4500000, 4000000, 3500000},
                                   {3500000, 3000000, 2500000},
                                   {2500000, 2000000, 1500000}};
    static double tunjangan[] = {800000, 600000, 400000};
    static double honor[][] = {{30000, 25000, 20000},
                               {25000, 20000, 15000},
                               {20000, 15000, 10000}};
    /**
     * Creates new form AplikasiGajiPegawai
     */
    public AplikasiGajiPegawai() {
        initComponents();
        
        CJenisPegawai.setModel(mdl);
        CJabatan.setModel(mdl1);
        TBLRincian.setModel(tbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LJudul = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        LNama = new javax.swing.JLabel();
        LJenisPegawai = new javax.swing.JLabel();
        LJabatan = new javax.swing.JLabel();
        LJumlahHari = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        TNama = new javax.swing.JTextField();
        CJenisPegawai = new javax.swing.JComboBox<>();
        CJabatan = new javax.swing.JComboBox<>();
        TJumlahHari = new javax.swing.JTextField();
        BHitung = new javax.swing.JButton();
        BReset = new javax.swing.JButton();
        Panel3 = new javax.swing.JPanel();
        LTotalGajiPNS = new javax.swing.JLabel();
        LTotalGajiNonPNS = new javax.swing.JLabel();
        LTotalGajiKontrak = new javax.swing.JLabel();
        Panel4 = new javax.swing.JPanel();
        TTotalGajiPNS = new javax.swing.JTextField();
        TTotalGajiNonPNS = new javax.swing.JTextField();
        TTotalGajiKontrak = new javax.swing.JTextField();
        SPTabel = new javax.swing.JScrollPane();
        TBLRincian = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gaji Pegawai");

        LJudul.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        LJudul.setForeground(new java.awt.Color(0, 0, 153));
        LJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LJudul.setText("Gaji Pegawai");

        LNama.setText("Nama");

        LJenisPegawai.setText("Jenis Pegawai");

        LJabatan.setText("Jabatan");

        LJumlahHari.setText("Jumlah Hari");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LNama)
                    .addComponent(LJenisPegawai)
                    .addComponent(LJabatan)
                    .addComponent(LJumlahHari))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LNama)
                .addGap(18, 18, 18)
                .addComponent(LJenisPegawai)
                .addGap(18, 18, 18)
                .addComponent(LJabatan)
                .addGap(18, 18, 18)
                .addComponent(LJumlahHari)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BHitung.setText("Hitung");
        BHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHitungActionPerformed(evt);
            }
        });

        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TNama)
                    .addComponent(CJenisPegawai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CJabatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TJumlahHari)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(BHitung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BReset)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addComponent(TNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CJenisPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TJumlahHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BHitung)
                    .addComponent(BReset)))
        );

        LTotalGajiPNS.setText("Total Gaji Pegawai PNS");

        LTotalGajiNonPNS.setText("Total Gaji Pegawai Tetap Non-PNS");

        LTotalGajiKontrak.setText("Total Gaji Pegawai Kontrak");

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LTotalGajiPNS)
                    .addComponent(LTotalGajiNonPNS)
                    .addComponent(LTotalGajiKontrak))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LTotalGajiPNS)
                .addGap(18, 18, 18)
                .addComponent(LTotalGajiNonPNS)
                .addGap(18, 18, 18)
                .addComponent(LTotalGajiKontrak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TTotalGajiPNS.setEditable(false);

        TTotalGajiNonPNS.setEditable(false);

        TTotalGajiKontrak.setEditable(false);

        javax.swing.GroupLayout Panel4Layout = new javax.swing.GroupLayout(Panel4);
        Panel4.setLayout(Panel4Layout);
        Panel4Layout.setHorizontalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TTotalGajiPNS)
                    .addComponent(TTotalGajiNonPNS)
                    .addComponent(TTotalGajiKontrak))
                .addContainerGap())
        );
        Panel4Layout.setVerticalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addComponent(TTotalGajiPNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TTotalGajiNonPNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TTotalGajiKontrak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TBLRincian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        SPTabel.setViewportView(TBLRincian);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SPTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addComponent(LJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJudul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHitungActionPerformed
        double jmlHari, gajiKotor, gajiBersih;
        int jnsPegawai = CJenisPegawai.getSelectedIndex(),
            nJabatan = CJabatan.getSelectedIndex();
        
        if (TNama.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nama", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }                                      
        if (TJumlahHari.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah hari", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            jmlHari = Double.valueOf(TJumlahHari.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Masukan jumlah hari harus berupa angka", "Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        gajiKotor = gajiPokok[jnsPegawai][nJabatan] + tunjangan[jnsPegawai] +
                    (honor[jnsPegawai][nJabatan] * jmlHari);
        gajiBersih = gajiKotor - (gajiKotor * 0.05);
        
        tbl.addRow(new Object[]{TNama.getText(), jenisPegawai[jnsPegawai],
                                jabatan[nJabatan], gajiKotor, gajiBersih});
        TBLRincian.setModel(tbl);
        
        buatTotalan();
    }//GEN-LAST:event_BHitungActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        TNama.setText(null);
        CJenisPegawai.setSelectedIndex(0);
        CJabatan.setSelectedIndex(0);
        TJumlahHari.setText(null);
        tbl.getDataVector().removeAllElements();
        tbl.fireTableDataChanged();
        buatTotalan();
    }//GEN-LAST:event_BResetActionPerformed

    public void buatTotalan() {
        int totalGaji[] = {0, 0, 0};
        
        for (int i = 0; i < TBLRincian.getRowCount(); i++) {
            for (int j = 0; j < 3; j++) {
                if (TBLRincian.getValueAt(i, 1).toString()
                        .equalsIgnoreCase(jenisPegawai[j])) {
                    totalGaji[j] += (double) TBLRincian.getValueAt(i, 4);
                }
            }
        }
        TTotalGajiPNS.setText(String.valueOf(totalGaji[0]));
        TTotalGajiNonPNS.setText(String.valueOf(totalGaji[1]));
        TTotalGajiKontrak.setText(String.valueOf(totalGaji[2]));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiGajiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiGajiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiGajiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiGajiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiGajiPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHitung;
    private javax.swing.JButton BReset;
    private javax.swing.JComboBox<String> CJabatan;
    private javax.swing.JComboBox<String> CJenisPegawai;
    private javax.swing.JLabel LJabatan;
    private javax.swing.JLabel LJenisPegawai;
    private javax.swing.JLabel LJudul;
    private javax.swing.JLabel LJumlahHari;
    private javax.swing.JLabel LNama;
    private javax.swing.JLabel LTotalGajiKontrak;
    private javax.swing.JLabel LTotalGajiNonPNS;
    private javax.swing.JLabel LTotalGajiPNS;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel4;
    private javax.swing.JScrollPane SPTabel;
    private javax.swing.JTable TBLRincian;
    private javax.swing.JTextField TJumlahHari;
    private javax.swing.JTextField TNama;
    private javax.swing.JTextField TTotalGajiKontrak;
    private javax.swing.JTextField TTotalGajiNonPNS;
    private javax.swing.JTextField TTotalGajiPNS;
    // End of variables declaration//GEN-END:variables
}
