
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hryzx
 */
public class AplikasiBMI extends javax.swing.JFrame {
    static String jenisKelamin[] = {"Laki-laki", "Perempuan"};
    DefaultComboBoxModel<String> mdl = new DefaultComboBoxModel(jenisKelamin);

    static Object kolom[] = {"Berat Badan", "Tinggi Badan", "Jenis Kelamin",
                             "BMI", "Kategori", "Berat Ideal"};
    int baris = 0;
    DefaultTableModel tbl = new DefaultTableModel(kolom, baris);

    /**
     * Creates new form AplikasiBMI
     */
    public AplikasiBMI() {
        initComponents();
        
        CJenisKelamin.setModel(mdl);
        TBLRincian.setModel(tbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LJudul = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        LBeratBadan = new javax.swing.JLabel();
        LTinggiBadan = new javax.swing.JLabel();
        LJenisKelamin = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        TBeratBadan = new javax.swing.JTextField();
        TTinggiBadan = new javax.swing.JTextField();
        CJenisKelamin = new javax.swing.JComboBox<>();
        BCek = new javax.swing.JButton();
        Panel3 = new javax.swing.JPanel();
        LBMI = new javax.swing.JLabel();
        LBBI = new javax.swing.JLabel();
        Panel4 = new javax.swing.JPanel();
        TBMI = new javax.swing.JTextField();
        TKategori = new javax.swing.JTextField();
        TBBI = new javax.swing.JTextField();
        SPTabel = new javax.swing.JScrollPane();
        TBLRincian = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Berat Badan Ideal");

        LJudul.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        LJudul.setForeground(new java.awt.Color(0, 0, 153));
        LJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LJudul.setText("Berat Badan Ideal");

        LBeratBadan.setText("Berat Badan:");

        LTinggiBadan.setText("Tinggi Badan:");

        LJenisKelamin.setText("Jenis Kelamin:");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBeratBadan)
                    .addComponent(LTinggiBadan)
                    .addComponent(LJenisKelamin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBeratBadan)
                .addGap(18, 18, 18)
                .addComponent(LTinggiBadan)
                .addGap(18, 18, 18)
                .addComponent(LJenisKelamin)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BCek.setText("Cek");
        BCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TBeratBadan)
                    .addComponent(TTinggiBadan)
                    .addComponent(CJenisKelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(BCek)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addComponent(TBeratBadan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TTinggiBadan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(BCek)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LBMI.setText("BMI / Kategori BMI:");

        LBBI.setText("Berat Badan Ideal:");

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBMI)
                    .addComponent(LBBI))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBMI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(LBBI)
                .addContainerGap())
        );

        TBMI.setEditable(false);

        TKategori.setEditable(false);

        TBBI.setEditable(false);

        javax.swing.GroupLayout Panel4Layout = new javax.swing.GroupLayout(Panel4);
        Panel4.setLayout(Panel4Layout);
        Panel4Layout.setHorizontalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TBBI)
                    .addGroup(Panel4Layout.createSequentialGroup()
                        .addComponent(TBMI, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Panel4Layout.setVerticalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TBMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TBBI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TBLRincian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        SPTabel.setViewportView(TBLRincian);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SPTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(LJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Panel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Panel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJudul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCekActionPerformed
        double beratBadan, tinggiBadan, nBMI, nBBI;
        String kategoriBMI;
        
        if (TBeratBadan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan berat badan", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (TTinggiBadan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan tinggi badan", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            beratBadan = Double.valueOf(TBeratBadan.getText());
            tinggiBadan = Double.valueOf(TTinggiBadan.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan harus berupa angka", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        nBMI = beratBadan / Math.pow((tinggiBadan / 100), 2);
        
        if (nBMI < 17) kategoriBMI = "Kurus";
        else if (nBMI >= 17 && nBMI < 23) kategoriBMI = "Normal";
        else if (nBMI >= 23 && nBMI < 27) kategoriBMI = "Kegemukan";
        else kategoriBMI = "Obesitas";
        
        TBMI.setText(String.valueOf(nBMI));
        TKategori.setText(kategoriBMI);
        
        if (CJenisKelamin.getSelectedIndex() == 0)
            nBBI = (tinggiBadan - 100) - ((tinggiBadan - 100) * 0.1);
        else
            nBBI = (tinggiBadan - 100) - ((tinggiBadan - 100) * 0.15);
        
        TBBI.setText(String.valueOf(nBBI));
        
        tbl.addRow(new Object[]{TBeratBadan.getText(), TTinggiBadan.getText(),
            jenisKelamin[CJenisKelamin.getSelectedIndex()], nBMI, kategoriBMI, nBBI});
        TBLRincian.setModel(tbl);
    }//GEN-LAST:event_BCekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiBMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiBMI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCek;
    private javax.swing.JComboBox<String> CJenisKelamin;
    private javax.swing.JLabel LBBI;
    private javax.swing.JLabel LBMI;
    private javax.swing.JLabel LBeratBadan;
    private javax.swing.JLabel LJenisKelamin;
    private javax.swing.JLabel LJudul;
    private javax.swing.JLabel LTinggiBadan;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel4;
    private javax.swing.JScrollPane SPTabel;
    private javax.swing.JTextField TBBI;
    private javax.swing.JTable TBLRincian;
    private javax.swing.JTextField TBMI;
    private javax.swing.JTextField TBeratBadan;
    private javax.swing.JTextField TKategori;
    private javax.swing.JTextField TTinggiBadan;
    // End of variables declaration//GEN-END:variables
}
