
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hryzx
 */
public class AplikasiKonversiSuhu extends javax.swing.JFrame {
    static String suhu[] = {"CELCIUS", "REAMUR", "KELVIN", "FARENHEIT"};
    DefaultComboBoxModel<String> mdl = new DefaultComboBoxModel(suhu),
                                 mdl1 = new DefaultComboBoxModel(suhu);

    static Object kolom[] = {"Suhu Awal", "Dari", "Ke", "Hasil Konversi"};
    int baris = 0;
    DefaultTableModel tbl = new DefaultTableModel(kolom, baris);

    /**
     * Creates new form AplikasiKonversiSuhu
     */
    public AplikasiKonversiSuhu() {
        initComponents();
        
        CDari.setModel(mdl);
        CKe.setModel(mdl1);
        TBLRincian.setModel(tbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LJudul = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        LSuhuAwal = new javax.swing.JLabel();
        LDari = new javax.swing.JLabel();
        LKe = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        TSuhuAwal = new javax.swing.JTextField();
        CDari = new javax.swing.JComboBox<>();
        CKe = new javax.swing.JComboBox<>();
        BKonversi = new javax.swing.JButton();
        Panel3 = new javax.swing.JPanel();
        LHasil = new javax.swing.JLabel();
        Panel4 = new javax.swing.JPanel();
        THasil = new javax.swing.JTextField();
        SPTabel = new javax.swing.JScrollPane();
        TBLRincian = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Konversi Suhu");

        LJudul.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        LJudul.setForeground(new java.awt.Color(0, 0, 153));
        LJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LJudul.setText("Konversi Suhu");

        LSuhuAwal.setText("Suhu Awal:");

        LDari.setText("Dari:");

        LKe.setText("Ke:");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LSuhuAwal)
                    .addComponent(LDari)
                    .addComponent(LKe))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LSuhuAwal)
                .addGap(18, 18, 18)
                .addComponent(LDari)
                .addGap(18, 18, 18)
                .addComponent(LKe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BKonversi.setText("Konversi");
        BKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKonversiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CKe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TSuhuAwal)
                    .addComponent(CDari, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(BKonversi)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addComponent(TSuhuAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(BKonversi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LHasil.setText("Hasil:");

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LHasil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LHasil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        THasil.setEditable(false);

        javax.swing.GroupLayout Panel4Layout = new javax.swing.GroupLayout(Panel4);
        Panel4.setLayout(Panel4Layout);
        Panel4Layout.setHorizontalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(THasil)
                .addContainerGap())
        );
        Panel4Layout.setVerticalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addComponent(THasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        TBLRincian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        SPTabel.setViewportView(TBLRincian);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SPTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(LJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJudul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SPTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKonversiActionPerformed
        double suhuAwal, hasilKonversi;
        
        if (TSuhuAwal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan suhu awal", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            suhuAwal = Double.valueOf(TSuhuAwal.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukan harus berupa angka", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        switch (CKe.getSelectedIndex()) {
            case 0:
                hasilKonversi = keCelcius(CDari.getSelectedIndex(), suhuAwal);
                break;
            case 1:
                hasilKonversi = keReamur(CDari.getSelectedIndex(), suhuAwal);
                break;
            case 2:
                hasilKonversi = keKelvin(CDari.getSelectedIndex(), suhuAwal);
                break;
            case 3:
                hasilKonversi = keFarenheit(CDari.getSelectedIndex(), suhuAwal);
                break;
            default:
                hasilKonversi = 0;
                break;
        }
        
        THasil.setText(String.valueOf(hasilKonversi));
        tbl.addRow(new Object[]{TSuhuAwal.getText(), suhu[CDari.getSelectedIndex()], 
                    suhu[CKe.getSelectedIndex()], hasilKonversi});
        TBLRincian.setModel(tbl);
    }//GEN-LAST:event_BKonversiActionPerformed

    public double keCelcius(int dari, double suhuAwal) {
        switch (dari) {
            case 0: // celcius
                return suhuAwal;
            case 1: // reamur
                return 5 * suhuAwal / 4;
            case 2: // kelvin
                return suhuAwal - 273;
            case 3: // farenheit
                return 5 * (suhuAwal - 32) / 9;
            default:
                return 0;
        }
    }
    
    public double keReamur(int dari, double suhuAwal) {
        switch (dari) {
            case 0: // celcius
                return 4 * suhuAwal / 5;
            case 1: // reamur
                return suhuAwal;
            case 2: // kelvin
                return 4 * suhuAwal / 5 - 273;
            case 3: // farenheit
                return 4 * suhuAwal / 9 - 32;
            default:
                return 0;
        }
    }
    
    public double keKelvin(int dari, double suhuAwal) {
        switch (dari) {
            case 0: // celcius
                return suhuAwal + 273;
            case 1: // reamur
                return 5 * suhuAwal / 4 + 273;
            case 2: // kelvin
                return suhuAwal;
            case 3: // farenheit
                return 5 * (suhuAwal - 32) / 9 + 273;
            default:
                return 0;
        }
    }
    
    public double keFarenheit(int dari, double suhuAwal) {
        switch (dari) {
            case 0: // celcius
                return 9 * suhuAwal / 5 + 32;
            case 1: // reamur
                return 9 * suhuAwal / 4 + 32;
            case 2: // kelvin
                return 9 * (suhuAwal - 273) / 5 + 32;
            case 3: // farenheit
                return suhuAwal;
            default:
                return 0;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BKonversi;
    private javax.swing.JComboBox<String> CDari;
    private javax.swing.JComboBox<String> CKe;
    private javax.swing.JLabel LDari;
    private javax.swing.JLabel LHasil;
    private javax.swing.JLabel LJudul;
    private javax.swing.JLabel LKe;
    private javax.swing.JLabel LSuhuAwal;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel4;
    private javax.swing.JScrollPane SPTabel;
    private javax.swing.JTable TBLRincian;
    private javax.swing.JTextField THasil;
    private javax.swing.JTextField TSuhuAwal;
    // End of variables declaration//GEN-END:variables
}
