
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hryzx
 */
public class bidangPersegiPanjang extends javax.swing.JFrame {
    DefaultComboBoxModel<String> mdl = new DefaultComboBoxModel();
    
    static Object kolom[] = {"Panjang", "Lebar", "Jenis", "Hasil"};
    int baris = 0;
    DefaultTableModel tbl = new DefaultTableModel(kolom, baris);
    /**
     * Creates new form bidangPersegiPanjang
     */
    public bidangPersegiPanjang() {
        initComponents();
        
        TNama.setEditable(false);
        
        mdl.addElement("--Pilih Hitung--");
        mdl.addElement("Keliling");
        mdl.addElement("Luas");
        CHitung.setModel(mdl);
        
        TabelPersegiPanjang.setModel(tbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LJudul = new javax.swing.JLabel();
        PanelTabel = new javax.swing.JScrollPane();
        TabelPersegiPanjang = new javax.swing.JTable();
        PanelKanan = new javax.swing.JPanel();
        TNama = new javax.swing.JTextField();
        TPanjang = new javax.swing.JTextField();
        TLebar = new javax.swing.JTextField();
        CHitung = new javax.swing.JComboBox<>();
        BProses = new javax.swing.JButton();
        PanelKiri = new javax.swing.JPanel();
        LNamaBidang = new javax.swing.JLabel();
        LPanjang = new javax.swing.JLabel();
        LLebar = new javax.swing.JLabel();
        LHitung = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bidang Persegi Panjang");

        LJudul.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        LJudul.setForeground(new java.awt.Color(51, 0, 153));
        LJudul.setText("Bidang Persegi Panjang");
        LJudul.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        TabelPersegiPanjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PanelTabel.setViewportView(TabelPersegiPanjang);

        TNama.setText("Persegi Panjang");

        BProses.setText("Proses");
        BProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BProsesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelKananLayout = new javax.swing.GroupLayout(PanelKanan);
        PanelKanan.setLayout(PanelKananLayout);
        PanelKananLayout.setHorizontalGroup(
            PanelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TNama)
                    .addComponent(TLebar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CHitung, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TPanjang)
                    .addGroup(PanelKananLayout.createSequentialGroup()
                        .addComponent(BProses)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelKananLayout.setVerticalGroup(
            PanelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CHitung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BProses)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LNamaBidang.setText("Nama Bidang:");

        LPanjang.setText("Panjang:");

        LLebar.setText("Lebar:");

        LHitung.setText("Hitung:");

        javax.swing.GroupLayout PanelKiriLayout = new javax.swing.GroupLayout(PanelKiri);
        PanelKiri.setLayout(PanelKiriLayout);
        PanelKiriLayout.setHorizontalGroup(
            PanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKiriLayout.createSequentialGroup()
                        .addComponent(LNamaBidang)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelKiriLayout.createSequentialGroup()
                        .addGroup(PanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LPanjang)
                            .addComponent(LLebar)
                            .addComponent(LHitung))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelKiriLayout.setVerticalGroup(
            PanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LNamaBidang)
                .addGap(18, 18, 18)
                .addComponent(LPanjang)
                .addGap(18, 18, 18)
                .addComponent(LLebar)
                .addGap(18, 18, 18)
                .addComponent(LHitung)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LJudul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PanelKiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelKanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJudul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelKanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelKiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PanelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BProsesActionPerformed
        double panjang, lebar;
        
        if (TPanjang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Panjang tidak boleh kosong", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (TLebar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lebar tidak boleh kosong", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            panjang = Double.parseDouble(TPanjang.getText());
            lebar = Double.parseDouble(TLebar.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukan harus berupa angka", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        switch (CHitung.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(this, "Pilih opsi hitung", "Error", JOptionPane.WARNING_MESSAGE);
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Nama:\t" + TNama.getText() +
                                                    "\nPanjang:\t" + TPanjang.getText() +
                                                    "\nLebar:\t" + TLebar.getText() +
                                                    "\nKeliling:\t" + (2 * (panjang + lebar)),
                                                    "Hasil", JOptionPane.INFORMATION_MESSAGE);
                tbl.addRow(new Object[]{TPanjang.getText(), TLebar.getText(), CHitung.getSelectedItem(), (2 * (panjang + lebar))});
                TabelPersegiPanjang.setModel(tbl);
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Nama:\t" + TNama.getText() +
                                                    "\nPanjang:\t" + TPanjang.getText() +
                                                    "\nLebar:\t" + TLebar.getText() +
                                                    "\nLuas:\t" + (panjang * lebar),
                                                    "Hasil", JOptionPane.INFORMATION_MESSAGE);
                tbl.addRow(new Object[]{TPanjang.getText(), TLebar.getText(), CHitung.getSelectedItem(), (panjang * lebar)});
                TabelPersegiPanjang.setModel(tbl);
                break;
        }
    }//GEN-LAST:event_BProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bidangPersegiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bidangPersegiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bidangPersegiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bidangPersegiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bidangPersegiPanjang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BProses;
    private javax.swing.JComboBox<String> CHitung;
    private javax.swing.JLabel LHitung;
    private javax.swing.JLabel LJudul;
    private javax.swing.JLabel LLebar;
    private javax.swing.JLabel LNamaBidang;
    private javax.swing.JLabel LPanjang;
    private javax.swing.JPanel PanelKanan;
    private javax.swing.JPanel PanelKiri;
    private javax.swing.JScrollPane PanelTabel;
    private javax.swing.JTextField TLebar;
    private javax.swing.JTextField TNama;
    private javax.swing.JTextField TPanjang;
    private javax.swing.JTable TabelPersegiPanjang;
    // End of variables declaration//GEN-END:variables
}
