
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hryzx
 */
public class AplikasiKonversiAngkaKeHuruf extends javax.swing.JFrame {
    static Object kolom[] = {"Angka", "Huruf"};
    int baris = 0;
    DefaultTableModel tbl = new DefaultTableModel(kolom, baris);
    
    static String satuan[] = {"nol", "satu", "dua", "tiga", "empat",
                              "lima", "enam", "tujuh", "delapan", "sembilan"};
    static String str0[] = {"se", "belas", "puluh", "ratus"};
    
    /**
     * Creates new form AplikasiKonversiAngkaKeHuruf
     */
    public AplikasiKonversiAngkaKeHuruf() {
        initComponents();
        
        TBLRincian.setModel(tbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LJudul = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        LAngka = new javax.swing.JLabel();
        LHuruf = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        TAngka = new javax.swing.JTextField();
        BKonversi = new javax.swing.JButton();
        THuruf = new javax.swing.JTextField();
        SPTabel = new javax.swing.JScrollPane();
        TBLRincian = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Konversi Angka ke Huruf");

        LJudul.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        LJudul.setForeground(new java.awt.Color(0, 0, 153));
        LJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LJudul.setText("Konversi Angka ke Huruf 1 - 100");

        LAngka.setText("Angka:");

        LHuruf.setText("Huruf:");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LAngka)
                    .addComponent(LHuruf))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LAngka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(LHuruf)
                .addContainerGap())
        );

        BKonversi.setText("Konversi");
        BKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKonversiActionPerformed(evt);
            }
        });

        THuruf.setEditable(false);

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TAngka)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(BKonversi)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(THuruf))
                .addContainerGap())
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addComponent(TAngka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(BKonversi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(THuruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TBLRincian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        SPTabel.setViewportView(TBLRincian);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SPTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(LJudul, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJudul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SPTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKonversiActionPerformed
        String angka, hasil = "";
        int iAngka;
        
        if (TAngka.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan angka", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            iAngka = Integer.valueOf(TAngka.getText());
            if (iAngka > 100) {
                JOptionPane.showMessageDialog(this, "Melampaui batas maksimum", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan harus berupa angka", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        angka = TAngka.getText();
        hasil = keHuruf(angka, iAngka);
//        test();
        
        THuruf.setText(hasil);
        tbl.addRow(new Object[]{TAngka.getText(), hasil});
        TBLRincian.setModel(tbl);
    }//GEN-LAST:event_BKonversiActionPerformed
    
    private void test() {
        for (int i = 0; i <= 100; i++) {
            String angka = Integer.toString(i);
            String hasil = keHuruf(angka, i);
            tbl.addRow(new Object[]{angka, hasil});
            TBLRincian.setModel(tbl);
        }
    }
    
    public String keHuruf(String angka, int iAngka) {
        String hasil;
        
        if (angka.length() == 1) {
            hasil = satuan[iAngka];
        } else if (angka.length() == 2) {
            if (angka.substring(1, 2).equals("0")) {    // _0
                if (iAngka == 10) {
                    hasil = str0[0] + str0[2];
                } else {
                    hasil = satuan[Integer.valueOf(angka.substring(0, 1))] +
                            " " + str0[2];
                }
            } else {
                if (iAngka == 11) {
                    hasil = str0[0] + str0[1];
                } else if (angka.substring(0, 1).equals("1")) {    // 1_
                    hasil = satuan[Integer.valueOf(angka.substring(1, 2))] +
                            " " + str0[1];
                } else {
                    hasil = satuan[Integer.valueOf(angka.substring(0, 1))] +
                            " " + str0[2] + 
                            " " + satuan[Integer.valueOf(angka.substring(1, 2))];
                }
            }
        } else if (angka.length() == 3) {
            if (iAngka == 100) {
                hasil = str0[0] + str0[3];
            } else hasil = "";
        } else {
            hasil = "";
        }
        
        return hasil;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiAngkaKeHuruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiAngkaKeHuruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiAngkaKeHuruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiAngkaKeHuruf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKonversiAngkaKeHuruf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BKonversi;
    private javax.swing.JLabel LAngka;
    private javax.swing.JLabel LHuruf;
    private javax.swing.JLabel LJudul;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JScrollPane SPTabel;
    private javax.swing.JTextField TAngka;
    private javax.swing.JTable TBLRincian;
    private javax.swing.JTextField THuruf;
    // End of variables declaration//GEN-END:variables
}
