
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hryzx
 */
public class AplikasiKasir extends javax.swing.JFrame {
    static String namaBarang[] = {"---Pilih Barang---", "Buku Tulis", "Ballpoint",
                                "Pensil", "Penghapus", "Penggaris", "Pensil Warna",
                                "Tipex", "Spidol", "Lem Uhu", "Stabilo"};
    static int hargaBarang[] = {25000, 5000, 4000, 3000, 7000, 45000, 10000,
                                8000, 6000, 15000};
    DefaultComboBoxModel<String> mdl = new DefaultComboBoxModel(namaBarang);
    
    static Object kolom[] = {"Nama Barang", "Harga", "Jumlah", "Subtotal"};
    int baris = 0;
    DefaultTableModel tbl = new DefaultTableModel(kolom, baris);
    /**
     * Creates new form AplikasiKasir
     */
    public AplikasiKasir() {
        initComponents();
        
        TBLRincian.setDefaultEditor(Object.class, null);
        CNamaBarang.setModel(mdl);
        TBLRincian.setModel(tbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LJudul = new javax.swing.JLabel();
        PanelKananAtas = new javax.swing.JPanel();
        SubPanelKananAtas = new javax.swing.JPanel();
        TSubtotal = new javax.swing.JTextField();
        BHapus = new javax.swing.JButton();
        CNamaBarang = new javax.swing.JComboBox<>();
        THarga = new javax.swing.JTextField();
        TJumlah = new javax.swing.JTextField();
        BTambah = new javax.swing.JButton();
        BReset = new javax.swing.JButton();
        PanelKiriAtas = new javax.swing.JPanel();
        LNamaBarang = new javax.swing.JLabel();
        LHarga = new javax.swing.JLabel();
        LJumlah = new javax.swing.JLabel();
        SubPanelKiriAtas = new javax.swing.JPanel();
        LSubtotal = new javax.swing.JLabel();
        SPTabel = new javax.swing.JScrollPane();
        TBLRincian = new javax.swing.JTable();
        PanelKiriBawah = new javax.swing.JPanel();
        LTotal = new javax.swing.JLabel();
        LDiskon = new javax.swing.JLabel();
        LBayar = new javax.swing.JLabel();
        PanelKananBawah = new javax.swing.JPanel();
        TTotal = new javax.swing.JTextField();
        TDiskon = new javax.swing.JTextField();
        TBayar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplikasi Kasir");

        LJudul.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LJudul.setForeground(new java.awt.Color(0, 0, 153));
        LJudul.setText("APLIKASI KASIR");
        LJudul.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        TSubtotal.setEditable(false);

        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubPanelKananAtasLayout = new javax.swing.GroupLayout(SubPanelKananAtas);
        SubPanelKananAtas.setLayout(SubPanelKananAtasLayout);
        SubPanelKananAtasLayout.setHorizontalGroup(
            SubPanelKananAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPanelKananAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubPanelKananAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TSubtotal)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubPanelKananAtasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BHapus)))
                .addContainerGap())
        );
        SubPanelKananAtasLayout.setVerticalGroup(
            SubPanelKananAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPanelKananAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BHapus)
                .addContainerGap())
        );

        CNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNamaBarangActionPerformed(evt);
            }
        });

        THarga.setEditable(false);

        TJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TJumlahKeyReleased(evt);
            }
        });

        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });

        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelKananAtasLayout = new javax.swing.GroupLayout(PanelKananAtas);
        PanelKananAtas.setLayout(PanelKananAtasLayout);
        PanelKananAtasLayout.setHorizontalGroup(
            PanelKananAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKananAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKananAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CNamaBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(THarga)
                    .addComponent(TJumlah)
                    .addGroup(PanelKananAtasLayout.createSequentialGroup()
                        .addComponent(BTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BReset)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(SubPanelKananAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelKananAtasLayout.setVerticalGroup(
            PanelKananAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKananAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(THarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelKananAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTambah)
                    .addComponent(BReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubPanelKananAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LNamaBarang.setText("Nama Barang");

        LHarga.setText("Harga");

        LJumlah.setText("Jumlah");

        LSubtotal.setText("Subtotal");

        javax.swing.GroupLayout SubPanelKiriAtasLayout = new javax.swing.GroupLayout(SubPanelKiriAtas);
        SubPanelKiriAtas.setLayout(SubPanelKiriAtasLayout);
        SubPanelKiriAtasLayout.setHorizontalGroup(
            SubPanelKiriAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPanelKiriAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LSubtotal)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        SubPanelKiriAtasLayout.setVerticalGroup(
            SubPanelKiriAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPanelKiriAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LSubtotal)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelKiriAtasLayout = new javax.swing.GroupLayout(PanelKiriAtas);
        PanelKiriAtas.setLayout(PanelKiriAtasLayout);
        PanelKiriAtasLayout.setHorizontalGroup(
            PanelKiriAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKiriAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKiriAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LNamaBarang)
                    .addComponent(LHarga)
                    .addComponent(LJumlah))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelKiriAtasLayout.createSequentialGroup()
                .addComponent(SubPanelKiriAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelKiriAtasLayout.setVerticalGroup(
            PanelKiriAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKiriAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LNamaBarang)
                .addGap(18, 18, 18)
                .addComponent(LHarga)
                .addGap(18, 18, 18)
                .addComponent(LJumlah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubPanelKiriAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TBLRincian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        SPTabel.setViewportView(TBLRincian);

        LTotal.setText("Total");

        LDiskon.setText("Diskon");

        LBayar.setText("Bayar");

        javax.swing.GroupLayout PanelKiriBawahLayout = new javax.swing.GroupLayout(PanelKiriBawah);
        PanelKiriBawah.setLayout(PanelKiriBawahLayout);
        PanelKiriBawahLayout.setHorizontalGroup(
            PanelKiriBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKiriBawahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKiriBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LTotal)
                    .addComponent(LDiskon)
                    .addComponent(LBayar))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        PanelKiriBawahLayout.setVerticalGroup(
            PanelKiriBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKiriBawahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LTotal)
                .addGap(18, 18, 18)
                .addComponent(LDiskon)
                .addGap(18, 18, 18)
                .addComponent(LBayar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TTotal.setEditable(false);

        TDiskon.setEditable(false);

        TBayar.setEditable(false);

        javax.swing.GroupLayout PanelKananBawahLayout = new javax.swing.GroupLayout(PanelKananBawah);
        PanelKananBawah.setLayout(PanelKananBawahLayout);
        PanelKananBawahLayout.setHorizontalGroup(
            PanelKananBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKananBawahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKananBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(TDiskon)
                    .addComponent(TBayar))
                .addContainerGap())
        );
        PanelKananBawahLayout.setVerticalGroup(
            PanelKananBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKananBawahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelKiriBawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelKananBawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(SPTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelKiriAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelKananAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelKiriAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelKananAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelKiriBawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelKananBawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNamaBarangActionPerformed
        if (CNamaBarang.getSelectedIndex() > 0) {
            THarga.setText(String.valueOf(hargaBarang[CNamaBarang.getSelectedIndex() - 1]));
            TJumlah.setText("1");
            TSubtotal.setText(String.valueOf(hargaBarang[CNamaBarang
                        .getSelectedIndex() - 1] * Integer.parseInt(TJumlah.getText())));
        } else {
            THarga.setText(null);
            TJumlah.setText(null);
        }
    }//GEN-LAST:event_CNamaBarangActionPerformed

    private void TJumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TJumlahKeyReleased
        try {
            TSubtotal.setText(String.valueOf(hargaBarang[CNamaBarang
                    .getSelectedIndex() - 1] * Integer.parseInt(TJumlah.getText())));
        } catch (NumberFormatException e) {
            TSubtotal.setText(null);
        }
    }//GEN-LAST:event_TJumlahKeyReleased

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        int harga, jumlah, subtotal;
        
        if (CNamaBarang.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Masukkan nama barang", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (TJumlah.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah barang", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            harga = Integer.parseInt(THarga.getText());
            jumlah = Integer.parseInt(TJumlah.getText());
            subtotal = Integer.parseInt(TSubtotal.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukan harus berupa angka", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
            
        tbl.addRow(new Object[]{namaBarang[CNamaBarang.getSelectedIndex()], harga, jumlah, subtotal});
        TBLRincian.setModel(tbl);
        buatTotalan();
    }//GEN-LAST:event_BTambahActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        while (TBLRincian.getSelectedRow() != -1) {
            baris = TBLRincian.getSelectedRow();
            tbl.removeRow(baris);
        }
        buatTotalan();
    }//GEN-LAST:event_BHapusActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        CNamaBarang.setSelectedIndex(0);
        THarga.setText(null);
        TJumlah.setText(null);
        TSubtotal.setText(null);
        tbl.getDataVector().removeAllElements();
        tbl.fireTableDataChanged();
        TTotal.setText(null);
        TDiskon.setText(null);
        TBayar.setText(null);
    }//GEN-LAST:event_BResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKasir().setVisible(true);
            }
        });
    }
    
    public void buatTotalan() {
        int total = 0, diskon = 0, bayar;
        for (int i = 0; i < TBLRincian.getRowCount(); i++) {
            total += (int) TBLRincian.getValueAt(i, 3);
        }
        if (total > 100000) diskon = total * 5 / 100;
        bayar = total - diskon;
        TTotal.setText(String.valueOf(total));
        TDiskon.setText(String.valueOf(diskon));
        TBayar.setText(String.valueOf(bayar));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BReset;
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox<String> CNamaBarang;
    private javax.swing.JLabel LBayar;
    private javax.swing.JLabel LDiskon;
    private javax.swing.JLabel LHarga;
    private javax.swing.JLabel LJudul;
    private javax.swing.JLabel LJumlah;
    private javax.swing.JLabel LNamaBarang;
    private javax.swing.JLabel LSubtotal;
    private javax.swing.JLabel LTotal;
    private javax.swing.JPanel PanelKananAtas;
    private javax.swing.JPanel PanelKananBawah;
    private javax.swing.JPanel PanelKiriAtas;
    private javax.swing.JPanel PanelKiriBawah;
    private javax.swing.JScrollPane SPTabel;
    private javax.swing.JPanel SubPanelKananAtas;
    private javax.swing.JPanel SubPanelKiriAtas;
    private javax.swing.JTable TBLRincian;
    private javax.swing.JTextField TBayar;
    private javax.swing.JTextField TDiskon;
    private javax.swing.JTextField THarga;
    private javax.swing.JTextField TJumlah;
    private javax.swing.JTextField TSubtotal;
    private javax.swing.JTextField TTotal;
    // End of variables declaration//GEN-END:variables
}
