
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hryzx
 */
public class KHSMahasiswa extends javax.swing.JFrame {
    static String mataKuliah[] = {"---Pilih Mata Kuliah---", "Pendidikan Agama",
                            "Matematika Komputasi", "Algoritma dan Pemrograman",
                            "Dasar Teknologi Informasi", "Jaringan Komputer",
                            "Pemrograman Mobile"};
    static int sks[] = {2, 2, 3, 3, 4, 4};
    DefaultComboBoxModel<String> mdl = new DefaultComboBoxModel(mataKuliah);

    static Object kolom[] = {"Mata Kuliah", "SKS", "Nilai Angka", "Nilai Huruf"};
    int baris = 0;
    DefaultTableModel tbl = new DefaultTableModel(kolom, baris);
    
    static Map<String, Object> defNilaiHuruf = Map.of("A", 4, "B+", 3.5,
            "B", 3, "C+", 2.5, "C", 2, "D+", 1.5, "D", 1, "E", 1);
    /**
     * Creates new form KHSMahasiswa
     */
    public KHSMahasiswa() {
        initComponents();
        
        TBLRincian.setDefaultEditor(Object.class, null);
        CMataKuliah.setModel(mdl);
        TBLRincian.setModel(tbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LJudul = new javax.swing.JLabel();
        PanelKiriAtas = new javax.swing.JPanel();
        LNama0 = new javax.swing.JLabel();
        LNim0 = new javax.swing.JLabel();
        LMataKuliah = new javax.swing.JLabel();
        LSks = new javax.swing.JLabel();
        LNilaiUts = new javax.swing.JLabel();
        LNilaiUas = new javax.swing.JLabel();
        LNilaiUkk = new javax.swing.JLabel();
        PanelKananAtas = new javax.swing.JPanel();
        LNama1 = new javax.swing.JLabel();
        LNim1 = new javax.swing.JLabel();
        CMataKuliah = new javax.swing.JComboBox<>();
        TSks = new javax.swing.JTextField();
        TNilaiUts = new javax.swing.JTextField();
        TNilaiUas = new javax.swing.JTextField();
        TNilaiUkk = new javax.swing.JTextField();
        BTambah = new javax.swing.JButton();
        BReset = new javax.swing.JButton();
        SPTabel = new javax.swing.JScrollPane();
        TBLRincian = new javax.swing.JTable();
        PanelIPK = new javax.swing.JPanel();
        LIpk = new javax.swing.JLabel();
        TIpk = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KHS Mahasiswa");

        LJudul.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LJudul.setForeground(new java.awt.Color(0, 0, 153));
        LJudul.setText("KHS MAHASISWA");
        LJudul.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        LNama0.setText("Nama");

        LNim0.setText("NIM");

        LMataKuliah.setText("Mata Kuliah");

        LSks.setText("SKS");

        LNilaiUts.setText("Nilai UTS (15%)");

        LNilaiUas.setText("Nilai UAS (15%)");

        LNilaiUkk.setText("Nilai UKK (70%)");

        javax.swing.GroupLayout PanelKiriAtasLayout = new javax.swing.GroupLayout(PanelKiriAtas);
        PanelKiriAtas.setLayout(PanelKiriAtasLayout);
        PanelKiriAtasLayout.setHorizontalGroup(
            PanelKiriAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKiriAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKiriAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LNama0)
                    .addComponent(LNim0)
                    .addComponent(LMataKuliah)
                    .addComponent(LSks)
                    .addComponent(LNilaiUts)
                    .addComponent(LNilaiUas)
                    .addComponent(LNilaiUkk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelKiriAtasLayout.setVerticalGroup(
            PanelKiriAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKiriAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LNama0)
                .addGap(18, 18, 18)
                .addComponent(LNim0)
                .addGap(18, 18, 18)
                .addComponent(LMataKuliah)
                .addGap(18, 18, 18)
                .addComponent(LSks)
                .addGap(18, 18, 18)
                .addComponent(LNilaiUts)
                .addGap(18, 18, 18)
                .addComponent(LNilaiUas)
                .addGap(18, 18, 18)
                .addComponent(LNilaiUkk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LNama1.setText("nama");
        LNama1.setText("Muhammad Haris Firmansyah");

        LNim1.setText("nim");
        LNim1.setText("203140914111044");

        CMataKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMataKuliahActionPerformed(evt);
            }
        });

        TSks.setEditable(false);

        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });

        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelKananAtasLayout = new javax.swing.GroupLayout(PanelKananAtas);
        PanelKananAtas.setLayout(PanelKananAtasLayout);
        PanelKananAtasLayout.setHorizontalGroup(
            PanelKananAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKananAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKananAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CMataKuliah, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TSks)
                    .addComponent(TNilaiUts)
                    .addComponent(TNilaiUas)
                    .addComponent(TNilaiUkk)
                    .addGroup(PanelKananAtasLayout.createSequentialGroup()
                        .addGroup(PanelKananAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LNama1)
                            .addComponent(LNim1)
                            .addGroup(PanelKananAtasLayout.createSequentialGroup()
                                .addComponent(BTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BReset)))
                        .addGap(0, 96, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelKananAtasLayout.setVerticalGroup(
            PanelKananAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKananAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LNama1)
                .addGap(18, 18, 18)
                .addComponent(LNim1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TNilaiUts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TNilaiUas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TNilaiUkk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelKananAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTambah)
                    .addComponent(BReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TBLRincian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        SPTabel.setViewportView(TBLRincian);

        LIpk.setText("IPK");

        TIpk.setEditable(false);

        javax.swing.GroupLayout PanelIPKLayout = new javax.swing.GroupLayout(PanelIPK);
        PanelIPK.setLayout(PanelIPKLayout);
        PanelIPKLayout.setHorizontalGroup(
            PanelIPKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIPKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LIpk)
                .addGap(99, 99, 99)
                .addComponent(TIpk)
                .addContainerGap())
        );
        PanelIPKLayout.setVerticalGroup(
            PanelIPKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIPKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIPKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LIpk)
                    .addComponent(TIpk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelIPK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SPTabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(PanelKiriAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelKananAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(LJudul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelKananAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelKiriAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelIPK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CMataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMataKuliahActionPerformed
        if (CMataKuliah.getSelectedIndex() > 0)
            TSks.setText(String.valueOf(sks[CMataKuliah.getSelectedIndex() - 1]));
        
        TNilaiUts.setText(null);
        TNilaiUas.setText(null);
        TNilaiUkk.setText(null);
    }//GEN-LAST:event_CMataKuliahActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        int nSks;
        double nilaiUts, nilaiUas, nilaiUkk, nilaiAkhir;
        String nilaiHuruf;
        
        if (CMataKuliah.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Masukkan mata kuliah", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (TNilaiUts.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nilai UTS", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (TNilaiUas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nilai UAS", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (TNilaiUkk.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nilai UKK", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            nSks = sks[CMataKuliah.getSelectedIndex() - 1];
            nilaiUts = Double.parseDouble(TNilaiUts.getText());
            nilaiUas = Double.parseDouble(TNilaiUas.getText());
            nilaiUkk = Double.parseDouble(TNilaiUkk.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukan harus berupa angka", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        nilaiAkhir = (nilaiUts * 0.15) + (nilaiUas * 0.15) + (nilaiUkk * 0.7);
        if (nilaiAkhir > 80) {
            nilaiHuruf = "A";
        } else if (nilaiAkhir > 75 && nilaiAkhir <= 80) {
            nilaiHuruf = "B+";
        } else if (nilaiAkhir > 70 && nilaiAkhir <= 75) {
            nilaiHuruf = "B";
        } else if (nilaiAkhir > 65 && nilaiAkhir <= 70) {
            nilaiHuruf = "C+";
        } else if (nilaiAkhir > 60 && nilaiAkhir <= 65) {
            nilaiHuruf = "C";
        } else if (nilaiAkhir > 55 && nilaiAkhir <= 60) {
            nilaiHuruf = "D+";
        } else if (nilaiAkhir > 50 && nilaiAkhir <= 55) {
            nilaiHuruf = "D";
        } else nilaiHuruf = "E";
        
        tbl.addRow(new Object[]{mataKuliah[CMataKuliah.getSelectedIndex()], nSks, nilaiAkhir, nilaiHuruf});
        TBLRincian.setModel(tbl);
        kalkulasiIPK();
    }//GEN-LAST:event_BTambahActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        CMataKuliah.setSelectedIndex(0);
        TSks.setText(null);
        TNilaiUts.setText(null);
        TNilaiUas.setText(null);
        TNilaiUkk.setText(null);
        tbl.getDataVector().removeAllElements();
        tbl.fireTableDataChanged();
        TIpk.setText(null);
    }//GEN-LAST:event_BResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KHSMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KHSMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KHSMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KHSMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KHSMahasiswa().setVisible(true);
            }
        });
    }
    
    public void kalkulasiIPK() {
        int nSks, totalSks = 0;
        double nilaiSkala, akumulasi = 0, totalIPK;
        String nilaiHuruf;
        
        for (int i = 0; i < TBLRincian.getRowCount(); i++) {
            nSks = (int) TBLRincian.getValueAt(i, 1);
            nilaiHuruf = (String) TBLRincian.getValueAt(i, 3);
            nilaiSkala = Double.valueOf(defNilaiHuruf.get(nilaiHuruf).toString());
            
            akumulasi += nilaiSkala * nSks;
            totalSks += nSks;
        }
        totalIPK = akumulasi / totalSks;
        TIpk.setText(String.valueOf(totalIPK));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BReset;
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox<String> CMataKuliah;
    private javax.swing.JLabel LIpk;
    private javax.swing.JLabel LJudul;
    private javax.swing.JLabel LMataKuliah;
    private javax.swing.JLabel LNama0;
    private javax.swing.JLabel LNama1;
    private javax.swing.JLabel LNilaiUas;
    private javax.swing.JLabel LNilaiUkk;
    private javax.swing.JLabel LNilaiUts;
    private javax.swing.JLabel LNim0;
    private javax.swing.JLabel LNim1;
    private javax.swing.JLabel LSks;
    private javax.swing.JPanel PanelIPK;
    private javax.swing.JPanel PanelKananAtas;
    private javax.swing.JPanel PanelKiriAtas;
    private javax.swing.JScrollPane SPTabel;
    private javax.swing.JTable TBLRincian;
    private javax.swing.JTextField TIpk;
    private javax.swing.JTextField TNilaiUas;
    private javax.swing.JTextField TNilaiUkk;
    private javax.swing.JTextField TNilaiUts;
    private javax.swing.JTextField TSks;
    // End of variables declaration//GEN-END:variables
}
