
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hryzx
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabAnggota = new javax.swing.JTabbedPane();
        PanelHaris = new javax.swing.JPanel();
        LImgHaris = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PanelAjeng = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PanelAsyroful = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuAplikasiKasir = new javax.swing.JMenuItem();
        MenuKHSMahasiswa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kelompok 8");
        setResizable(false);

        TabAnggota.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        PanelHaris.setOpaque(false);

        LImgHaris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/haris.jpg"))); // NOI18N

        jLabel1.setText("Nama:");

        jLabel4.setText("Muhammad Haris Firmansyah");

        jLabel5.setText("NIM:");

        jLabel6.setText("203140914111044");

        javax.swing.GroupLayout PanelHarisLayout = new javax.swing.GroupLayout(PanelHaris);
        PanelHaris.setLayout(PanelHarisLayout);
        PanelHarisLayout.setHorizontalGroup(
            PanelHarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHarisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LImgHaris)
                .addGap(18, 18, 18)
                .addGroup(PanelHarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelHarisLayout.setVerticalGroup(
            PanelHarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHarisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelHarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelHarisLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(LImgHaris))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        TabAnggota.addTab("Anggota 1", PanelHaris);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajeng.jpg"))); // NOI18N

        jLabel11.setText("Nama:");

        jLabel12.setText("Ajeng Riskiani Lestari");

        jLabel13.setText("NIM:");

        jLabel14.setText("203140914111047");

        javax.swing.GroupLayout PanelAjengLayout = new javax.swing.GroupLayout(PanelAjeng);
        PanelAjeng.setLayout(PanelAjengLayout);
        PanelAjengLayout.setHorizontalGroup(
            PanelAjengLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAjengLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(PanelAjengLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        PanelAjengLayout.setVerticalGroup(
            PanelAjengLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAjengLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAjengLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAjengLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabAnggota.addTab("Anggota 2", PanelAjeng);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asyroful.jpg"))); // NOI18N

        jLabel7.setText("Nama:");

        jLabel8.setText("Muhammad Asyroful Munna");

        jLabel9.setText("NIM:");

        jLabel10.setText("203140914111053");

        javax.swing.GroupLayout PanelAsyrofulLayout = new javax.swing.GroupLayout(PanelAsyroful);
        PanelAsyroful.setLayout(PanelAsyrofulLayout);
        PanelAsyrofulLayout.setHorizontalGroup(
            PanelAsyrofulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAsyrofulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(PanelAsyrofulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        PanelAsyrofulLayout.setVerticalGroup(
            PanelAsyrofulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAsyrofulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAsyrofulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAsyrofulLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addComponent(jLabel2))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        TabAnggota.addTab("Anggota 3", PanelAsyroful);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Selamat Datang di Tugas UAS Alpro");

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("KELOMPOK 8");

        jMenu1.setText("Project");

        MenuAplikasiKasir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuAplikasiKasir.setText("Aplikasi Kasir");
        MenuAplikasiKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAplikasiKasirActionPerformed(evt);
            }
        });
        jMenu1.add(MenuAplikasiKasir);

        MenuKHSMahasiswa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuKHSMahasiswa.setText("KHS Mahasiswa");
        MenuKHSMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKHSMahasiswaActionPerformed(evt);
            }
        });
        jMenu1.add(MenuKHSMahasiswa);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");

        MenuAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuAbout.setText("About");
        MenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAboutActionPerformed(evt);
            }
        });
        jMenu2.add(MenuAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TabAnggota)
                        .addContainerGap())
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(24, 24, 24)
                .addComponent(TabAnggota)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAplikasiKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAplikasiKasirActionPerformed
        AplikasiKasir aplikasiKasir = new AplikasiKasir();
        aplikasiKasir.setLocationRelativeTo(this);
        aplikasiKasir.setVisible(true);
    }//GEN-LAST:event_MenuAplikasiKasirActionPerformed

    private void MenuKHSMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKHSMahasiswaActionPerformed
        KHSMahasiswa kHSMahasiswa = new KHSMahasiswa();
        kHSMahasiswa.setLocationRelativeTo(this);
        kHSMahasiswa.setVisible(true);
    }//GEN-LAST:event_MenuKHSMahasiswaActionPerformed

    private void MenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAboutActionPerformed
        JOptionPane.showMessageDialog(this, "Kelompok 8\n\n" +
                                            "Muhammad Haris Firmansyah\n" +
                                            "Ajeng Riskiani Lestari\n" +
                                            "Muhammad Asyroful Munna\n\n" +
                                            "Source code juga tersedia di\n" +
                                            "http:\\\\tiny.cc\\kel8",
                                    "About Us", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_MenuAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LImgHaris;
    private javax.swing.JMenuItem MenuAbout;
    private javax.swing.JMenuItem MenuAplikasiKasir;
    private javax.swing.JMenuItem MenuKHSMahasiswa;
    private javax.swing.JPanel PanelAjeng;
    private javax.swing.JPanel PanelAsyroful;
    private javax.swing.JPanel PanelHaris;
    private javax.swing.JTabbedPane TabAnggota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
